### ISSUE TITLE
CSS Modules?

### ISSUE THREAD

**Issue by trodrigues** [petehunt/react-howto#25]
Would there be any interest in adding information about [CSS Modules](https://github.com/gajus/react-css-modules) to this?

It fixes all (?) of the issues with using inline styles while still allowing people to write CSS the way they used to and also fixing most of the issues that exist with CSS (composition, etc), and allowing them to still use SASS/Stylus if they want.

I can write it up and make a PR for this, but if it goes against the general philosophy of the document then I won't bother.

**Comment by petehunt** [comment]
I think it'd make sense to add a sentence or two in the "inline styles" section about using css modules.
