### ISSUE TITLE
Feedback on how to learn React

### ISSUE THREAD

**Issue by Klaasvaak** [petehunt/react-howto#3]
Saw you tweeting this: https://twitter.com/floydophone/status/684109201665208321 asking for feedback. So I decided to just do that in an issue, just close it if I should contact you somewhere else.

About "Learning React itself": I think the official tutorial is fine. But if you are a 'total newbie', why would you bother them with state in components? Just teach them: send data to a component and you are done. Does this data change? Repeat step 1.

Would like to hear what you think of this. A few weeks ago I teached some 2nd year students the basics of react, I never mentioned state.

**Comment by petehunt** [comment]
If you never mentioned state, how would you handle interactivity?

**Comment by Klaasvaak** [comment]
Well, it doesn't mean there is no state. There is just no state in components, so I never mentioned `getInitialState` and `setState`

**Comment by petehunt** [comment]
Interesting approach, and I've done something similar, but it's not really idiomatic React. Going to close this issue but feel free to reopen if needed.
