### ISSUE TITLE
Official tutorial changed

### ISSUE THREAD

**Issue by with0out** [petehunt/react-howto#65]
Their official [tutorial](https://facebook.github.io/react/docs/tutorial.html) (Comment box tutorial) recently changed to building a game "tic tac toe".
And I find this new version's instructions very difficult to follow comparing to the old one.
Maybe an re-evaluation of this tutorial?
Thanks.

**Comment by petehunt** [comment]
You should talk to @gaearon or @spicyj about this or open an issue on the react repo. I wrote the old tutorial and had nothing to do with the new one.

**Comment by spicyj** [comment]
@with0out Please comment on https://github.com/facebook/react/issues/8035 and explain what we could make clearer in the new tutorial. We think it gives a better introduction overall but it may have a few rough edges.
