### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cjbassi** [petehunt/react-howto#90]
Under [Learning React itself](https://github.com/petehunt/react-howto/blob/master/README.md#learning-react-itself), the [the official tutorial](https://facebook.github.io/react/docs/tutorial.html) link redirects me to https://tutorial/tutorial.html for some reason, which doesn't work.

**Comment by SpartaSixZero** [comment]
@cjbassi That's correct, looks like it was pointing to an older page which was moved to this one.

https://reactjs.org/tutorial/tutorial.html

I created a pull request below to address this issue:
https://github.com/petehunt/react-howto/pull/92

**Comment by SpartaSixZero** [comment]
Actually, just saw someone already addressed this here:

#91

I'll close mine.

**Comment by SpartaSixZero** [comment]
I just checked today and looks like they corrected the url redirect to point to the correct url. So this issue can probably be closed.
